### ISSUE TITLE
"TeX capacity exceeded" for some jobs

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#101]
Recently I have spotted several pipelines in more repositories to fail with this error and nothing else which would indicate an issue.

```
! TeX capacity exceeded, sorry [parameter stack size=20000].
\__regex_toks_clear:N #1->
                          \tex_toks:D #1={}
l.10 ...t=metadata]{example-document/metadata.yml}
```
https://github.com/istqborg/istqb_product_base/actions/runs/10341878717/job/28624450777#step:6:215

[This](https://github.com/istqborg/istqb_product_base/actions/runs/10341878717) job fails, but [re-run](https://github.com/istqborg/istqb_product_base/actions/runs/10341878719) worked fine. 

Is this something we can prevent?

**Comment by Witiko** [comment]
This seems like a transient issue caused by a temporary bug with the template. Is this issue something that you can currently see in any repository?

**Comment by danopolan** [comment]
Seems that this issue is not occurring anymore for the latest pipelines, so I am closing this Issue.
