### ISSUE TITLE
Changes in references for ISTQB template v4.2

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#105]
The latest updates in the ISTQB template require different chapter References and Further Reading layout.

The changes are as follows:

1. Web pages as `@online` should be added to sub-section _Web Pages_ instead of _Further Reading_
2. The Web pages section will have text at the end of the list as follows:
_"The previous references point to information available on the Internet and elsewhere. Even though those references were checked at the time of publication of this syllabus, the ISTQB® cannot be held responsible if the references are unavailable anymore."_
3. _Further Reading_ section will only contain uncited references. 
Also, is it possible to have a configurable option to show/hide uncited references?
5. There should be a possibility to add "Glossary References" section with list of links to online glossaries used in the syllabus. I am not sure if we can fulfil this requirement. It's not a high priority for now.   
<img width="339" alt="image" src="https://github.com/user-attachments/assets/e8c0d4de-b3f5-417e-872a-34c54f7fab6a">

6. Sections should be ordered as: Standards, ISTQB Documents, Glossary References, Books, Articles, Web Pages, Further reading.

**Comment by danopolan** [comment]
@mhamburg could you please review the specification?

**Comment by mhamburg** [comment]
- Books and Articles should stay separate subsections. I disagree here with the template v4.2.

- Use the subsection name 'Glossaries' rather than 'Glossary References' (Here too, I disagree with the template)

- The sequence of subsections in the References chapter shall be:

1. Standards
2. ISTQB(R) Documents
3. Glossaries
4. Books
5. Articles
6. Web Pages

- Only create a subsection if it contains entries.  
- If present, Further Reading shall be a separate chapter immediately following the References, preceding the Appendices. Further Reading has no subsections (for whichever type of reference).

**Comment by mhamburg** [comment]
I just sent an email to Processes because the template is quite confusing. Maybe we should merge some (or all) subsections, except for further reading.

**Comment by danopolan** [comment]
@Witiko are they any best practices for ISO690 and LaTeX in matter of referenced and bibliography? I have found ISO690 not specific enough and there are many other sources for best practices, which are sometimes contradictory. 
I want to follow existing academic standards, to which ISTQB will adapt.

**Comment by Witiko** [comment]
> The ISO 690 standard contains many optional parts that are open for interpretation by regional standardization bodies. Therefore, there are regional variations in how ISO 690 is used, which is by design.

Furthermore, ISO 690 specifies only the format of the references at the end of the document and not how they are cited within the document. Therefore, authors can use author-year citations such as (Doe, 1992), also known as the Harvard system, which we currently use, numeric citations such as [1], also known as the Vancouver system, or just place the full references into footnotes, which is commonly done in the humanities.

**Comment by mhamburg** [comment]
@danopolan - Can we adjust to the current template today? You aligned with Filipe the layout. Webpages should not be in a separate Ch. for Further Reading anymore. I want to submit the material by EOD.

**Comment by danopolan** [comment]
@Witiko I have updated the requirements and we can consider them final now.

**Comment by Witiko** [comment]
> 3. _Further Reading_ section will only contain uncited references.
>     Also, is it possible to have a configurable option to show/hide uncited references?

Since the section _Further Reading_ only contains uncited references and uncited references only occur in this section, would the options essentially show/hide the entire section _Further Reading_?

> 4. There should be a possibility to add "Glossary References" section with list of links to online glossaries used in the syllabus. I am not sure if we can fulfil this requirement. It's not a high priority for now.
> 
> <img alt="image" width="339" src="https://private-user-images.githubusercontent.com/95688217/361719018-e8c0d4de-b3f5-417e-872a-34c54f7fab6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTgzMzMsIm5iZiI6MTczMDc1ODAzMywicGF0aCI6Ii85NTY4ODIxNy8zNjE3MTkwMTgtZThjMGQ0ZGUtYjNmNS00MTdlLTg3MmEtMzRjNTRmN2ZhYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIyMDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMGJmY2E2ZWQ4MzExN2UwMzhlOWZlZmU3MTdmMTE5ZWE1NmY0MGQ3MjU4YjA0MWNjNWUzNTY4NTFkYzVkZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JghB0kAc2tRFlwRq03lXWocR9jB_GxD-hw1aF878pbY">

Could be the easiest to just type them in Markdown:

``` md
# Glossary References {-}
References for terminology used in this Syllabus:
- Agile Alliance: <https://www.agilealliance.org/agile-practice-guide/>
- IEEE/Pascal for software engineering: <https://pascal.computer.org/>
- IREB-CPRE for Requirements Engineering: <https://www.ireb.org/en/cpre/glossary>
- ISTQB® Glossary: <https://glossary.istab.org/>
```

**Comment by Witiko** [comment]
> 2. The Web pages section will have text at the end of the list as follows:
>       _"The previous references point to information available on the Internet and elsewhere. Even though those references were checked at the time of publication of this syllabus, the ISTQB® cannot be held responsible if the references are unavailable anymore."_

Does the standard specify German, Czech, and Slovak translations for this text or should I translate it myself?

**Comment by Witiko** [comment]
> 1. Web pages as `@online` should be added to sub-section _Web Pages_ instead of _Further Reading_

I made this change in commit c1d8ae1 from the PR-less branch `feat/istqb-template-v4.2`. Here is how it looks:

https://github.com/istqborg/istqb_product_base/blob/c1d8ae1d008c836b4498191aa67faf9c968f05b8/example-document/bibliography.bib#L1-L85

![image](https://github.com/user-attachments/assets/4a3b1914-d451-488e-8f32-7e052c4b0fc2)

**Comment by danopolan** [comment]
@mhamburg what do you think with the screenshot above? I am fine with it.
Additionally, we should be adding text as part of WebPages section.

_These references point to information available on the Internet and elsewhere. Even though those
references were checked at the time of publication of this syllabus, the ISTQB® cannot be held
responsible if the references are not available anymore._

**Comment by Witiko** [comment]
> Additionally, we should be adding text as part of WebPages section. [...]

I already addressed this in https://github.com/istqborg/istqb_product_base/issues/105#issuecomment-2455880836.

**Comment by danopolan** [comment]
**English**
The previous references point to information available on the Internet and elsewhere. Even though those references were checked at the time of publication of this syllabus, the ISTQB® cannot be held responsible if the references are unavailable anymore.

**German**
Coming in 30 mins

**Slovak**
Predchádzajúce referencie odkazujú na informácie dostupné na internete a inde. Aj keď boli tieto referencie skontrolované v čase zverejnenia tohto sylabu, ISTQB® nemôže byť brané na zodpovednosť, ak referencie už nie sú k dispozícii.

**Czech**
Předchozí reference odkazují na informace dostupné na internetu a jinde. I když byly tyto reference zkontrolovány v době zveřejnění tohoto sylabu, ISTQB® nemůže nést odpovědnost, pokud reference již nejsou k dispozici.

**Comment by Witiko** [comment]
> Yes, I am for this option since it's more consistent with other references.

Can you please also provide the German, Czech, and Slovak translation for the section "Glossary References" or confirm that we can use the following translations?

- **German:** Glossarverweise
- **Czech:** Odkazy na glosáře
- **Slovak:** Odkazy na glosáre

**Comment by danopolan** [comment]
> Can you please also provide the German, Czech, and Slovak translations for the section name "Glossary References" 

- **German:** Referenzen zu Glossaren
- **Czech:** Odkazy na slovníky
- **Slovak:** Odkazy na slovníky

**Comment by Witiko** [comment]
> References for terminology used in this Syllabus

I don't think we can correctly decline the document type (Syllabus) in Czech and Slovak. Can we write "document" instead of "Syllabus" to get around this issue? Furthermore, can you please also provide the German, Czech, and Slovak translations or confirm that we can use the following translations?

- **English:** References for terminology used in this document
- **German:** Referenzen für die in diesem Dokument verwendete Terminologie
- **Czech:** Odkazy na terminologii použitou v tomto dokumentu
- **Slovak:** Odkazy na terminológiu použitú v tomto dokumente

**Comment by danopolan** [comment]
Keet is simple and call it a "document". So, text will be as follow:

- **English:** References for terminology used in this document
- **German:** Referenzen für die im Lehrplan verwendeten Begriffe
- **Czech:** Odkazy na terminologii použitou v tomto dokumentu
- **Slovak:** Odkazy na terminológiu použitú v tomto dokumente

**Comment by danopolan** [comment]
Looks good from my side as well as from @mhamburg.

Is there a way around ISO690 formatting? Removing [n.p.] and text "Available also from:" would be enough. No need for having it as a list with colons.

**Comment by Witiko** [comment]
In commit d42df33 from the branch `feat/istqb-template-v4.2`, I fixed the formatting of the glossary references. Here is how the references look for the example document from this repository:

![image](https://github.com/user-attachments/assets/a96fdca6-f355-4c0c-b4a8-943532f5b940)

Here is how the same document would look in German (top), Czech (middle), and Slovak (bottom):

![image](https://github.com/user-attachments/assets/4466d3f0-9f4a-4ae7-a7e6-8fd13cdcb090)
![image](https://github.com/user-attachments/assets/043e05d1-4280-4360-ab8b-0445295dae3f)
![image](https://github.com/user-attachments/assets/9b507d9f-9584-445d-a126-c653f99a3e6d)

I opened PR https://github.com/istqborg/istqb_product_base/pull/135 that should close this ticket.
