### ISSUE TITLE
Sporadic incorrect indentation in the list of references 

### ISSUE THREAD

**Issue by mhamburg** [istqborg/istqb_product_base#119]
In the pdf syllabus, section references, some entries are not aligned left with the majority of the entries. I cannot see any difference in the source.  This includes ISTQB-PT, CHILLAREGE, and SEGURA (2020). Please see the screenshots attached from the current CTAL-TA pdf.

<img width="308" alt="Screenshot 2024-10-11 092853" src="https://github.com/user-attachments/assets/69c4780b-b4d2-461d-ad43-eb7922db9fba">

<img width="349" alt="Screenshot 2024-10-11 092925" src="https://github.com/user-attachments/assets/f05405f5-1cc2-4b01-9fbb-dd30d0bb959e">

<img width="344" alt="Screenshot 2024-10-11 092956" src="https://github.com/user-attachments/assets/dd0f9920-5a98-4632-8f6f-b83301870ae2">

**Comment by mhamburg** [comment]
@danopolan @Witiko - We have yet another indentation issue in the ToC:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/c866f7cb-faf3-43d9-9c9c-1f58c727cca8">

**Comment by danopolan** [comment]
This is reported as https://github.com/istqborg/istqb_product_base/issues/123
