### ISSUE TITLE
Traceability matrix text translation

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#121]
In the traceability matrix things still have to be translated for German, but also Czech and Slovak and get it ready for other languages.

![1000020188](https://github.com/user-attachments/assets/68eef1c9-657d-46cd-8877-65777ff8d618)

Verfolgbarkeitsmatrix des geschäftlichen Nutzens (Business Outcomes) mit Lernzielen

Dieser Abschnitt listet die Anzahl der Lernziele des vorliegenden Lehrplans auf, die mit dem geschäftlichen Nutzen in Verbindung stehen, sowie die Verfolgbarkeit zwischen dem geschäftlichen Nutzen des Lehrplans und den Lernzielen des Spezialist Syllabus Testautomatisierungsstrategie.

Business Outcomes == Geschäftlichen Nutzen

**Comment by Witiko** [comment]
"Business Outcomes", "Learning Objectives", and "Traceability matrix" seem like highly specific terms. Can you please also provide Czech and Slovak translations?

**Comment by danopolan** [comment]
Sorry did not realize that

| EN | DE | CZ | SK |
| --- | --- | --- | --- |
| Business Outcomes | Geschäftlichen Nutzen | Profesní cíle | Profesijné ciele | 
| Learning Objectives | Lernzielen | Studijní cíle | Študijné ciele |
| Traceability matrix | Verfolgbarkeitsmatrix | Trasovací matice | Trasovacia matica |

**Comment by Witiko** [comment]
I implemented the translations in PR https://github.com/istqborg/istqb_product_base/pull/126. See https://github.com/istqborg/istqb_product_base/pull/126#issue-2630053580 for a demonstration.
