### ISSUE TITLE
Page overflow in Traceability Matrix for TAE in German

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#131]
With TAE syllabus in German language ([main branch](https://github.com/istqborg/istqb-ct-tae)), we run into issue where the table overflows the page

<img width="447" alt="image" src="https://github.com/user-attachments/assets/48116b57-dffe-4e73-8cce-cc025ffe2546">

Can we add automatic line breaks in the second column to keep other columns from overflowing?

**Comment by Witiko** [comment]
This has been resolved in commit 1b0b3b3 from #147:

![image](https://github.com/user-attachments/assets/fb185cd2-bdcf-4b5c-80b4-d5980d7d870b)
![image](https://github.com/user-attachments/assets/f5e4cd0c-4100-4f49-a0e8-2fc0cbf261b8)
![image](https://github.com/user-attachments/assets/cb6a98d9-3cfe-47c7-a4cd-e6a9436dbb26)
