### ISSUE TITLE
Allow usage of U+2009 character

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#139]
German Testing Board has a request to support thin space unicode character U+2009 (https://www.compart.com/en/unicode/U+2009) for abbreviations.

I have tested it, and [PDF build fails](https://github.com/istqborg/istqb_product_template/actions/runs/11776516464/job/32799104280).

```
! LaTeX Error: Unicode character   (U+2009)
               not set up for use with LaTeX.
```

**Comment by Witiko** [comment]
The issue should be fixed in commit 9bfe2d1, see also [the passing build][1].

 [1]: https://github.com/istqborg/istqb_product_template/actions/runs/11776516464
