### ISSUE TITLE
Allow hypenation for German language

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#144]
Translation of TAE and TAS syllabi to German showed a need for splitting words at the end of the line.

Acceptance criteria:

- hypenation can be turned on and off via `metadata.yml`
- applies for all documents (syllabus, sample exams, etc.)
- only german language will be supported
- ~~hypenation is done in paragraph text only (avoid headings, ToC, etc.)~~
- documentation is updated

**Comment by Witiko** [comment]
> hypenation is done in paragraph text only (avoid headings, ToC, etc.)

Is this an important requirement? It's much easier and more common to enable hyphenation for the entire document.
