### ISSUE TITLE
Improve page breaks

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#145]
To address issues below, we need to change rules for applying page breaks.

The page break is applied when:
1. Heading is let alone on previous page > heading is moved to next page
  ![image](https://github.com/user-attachments/assets/edffc091-fe73-4076-8a93-6b0c97853d09)
2. One line of text is left on a previous page > line is moved to next page
  ![image (1)](https://github.com/user-attachments/assets/3b8726a0-e7aa-4093-9aa4-19a429eb324c)
3. One line of text is on the next page > one more line is moved to next page 
  ![image (2)](https://github.com/user-attachments/assets/c5e8d00e-a04d-439b-a2ed-e02e4cc44ab1)

**Comment by Witiko** [comment]
2 and 3 are not something that can be easily automated with the current backend (pdfTeX). We will need to switch to LuaTeX. In the meantime, if you'd like to be able to fix things manually, you can type ``` `\pagebreak`{=tex} ``` when you would like to break the current page.

**Comment by danopolan** [comment]
@anetader can you please update the documentation in `./example-document` with the info how to force a page break?

> if you'd like to fix things manually, you can type `` `\pagebreak`{=tex} `` when you would like to break the current page.
