### ISSUE TITLE
Heading text overflow in German TAS

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#146]
There is a heading text overflowing the box in TAS syllabus, chapter 2.1

<img width="815" alt="image" src="https://github.com/user-attachments/assets/222fdd5e-dc9a-4ec9-a52c-521bbcab2cab">

**Comment by danopolan** [comment]
@Witiko could this be resomved by #144 ?

**Comment by Witiko** [comment]
This has been resolved in commit 07dfb8b from #147:

![image](https://github.com/user-attachments/assets/9b7d1a63-e3f5-409a-9e74-92f972a10c90)
