### ISSUE TITLE
Two more translations missing in Traceability Matrix

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#148]
Create translation keys for the following text in Traceability Matrix

| English | German | Czech | Slovak |
| ------- | -------- | ------- | ------ |
| ~~Unique LO~~ LO Number | LO-Nummer | Číslo cíle | Číslo cieľa
| Learning Objective (K-level) | Lernziel (K-level)| Studijní cíl (úroveň) | Študijný cieľ (úroveň)

![image](https://github.com/user-attachments/assets/62acd988-2e4e-4db0-8771-4bafec4b2948)

**Comment by Witiko** [comment]
I fixed this in commit ad2e6f6c9a85bf5468e7f1d2cdaa9d03422db8fe from PR #150:

![Screenshot from 2024-11-26 15-51-41](https://github.com/user-attachments/assets/d62d48ba-c90c-4025-ba29-6c6c6fc9da86)
![Screenshot from 2024-11-26 15-51-19](https://github.com/user-attachments/assets/4fdfca27-1e29-43d3-b224-6d97d8069509)
![Screenshot from 2024-11-26 15-51-57](https://github.com/user-attachments/assets/b1086524-ff06-44a1-ba29-af526e9d079a)
![Screenshot from 2024-11-26 15-52-10](https://github.com/user-attachments/assets/92ac1940-2c9d-4eaf-ba94-32dc31982865)
