### ISSUE TITLE
Remove word "Syllabus" from traceability Matrix text

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#149]
Remove word "Syllabus", since it's not necessary there.

<img width="950" alt="image" src="https://github.com/user-attachments/assets/6e34b1dd-5e9a-42fa-a9df-259021ce70e3">

**Comment by Witiko** [comment]
Currently, we use the metadata values `level` (Advanced Level), `type` (Syllabus), and `title` (Test Automation Engineering) to construct the section name and the description:

https://github.com/istqborg/istqb_product_base/blob/648e95d2a2423c6dfe3c76ae98846594487f647e/template/markdownthemeistqb_common.sty#L519-L549
https://github.com/istqborg/istqb_product_base/blob/648e95d2a2423c6dfe3c76ae98846594487f647e/template/markdownthemeistqb_common.sty#L728-L767

Your requirement is to use just `level`, followed by `title`, correct?

**Comment by Witiko** [comment]
I fixed this in commit 1c90e13c from PR #150:

![image](https://github.com/user-attachments/assets/d8a83f4f-936d-41bf-80ae-582e6c769bb2)
![image](https://github.com/user-attachments/assets/2f6a579e-3dd3-4f52-8c53-a816fc4d38df)
