### ISSUE TITLE
Page breaks should not split heading and text

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#24]
In several documents, there is an issue that heading is left one page, but text is on another page. See e.g. CTFL-SK syllabus in build https://github.com/istqborg/istqb_ctfl/actions/runs/8360553342 where there are splits like this in the Table of Content and some chapters.

Examples:
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/b5bbd566-fa46-4b99-9de9-860071968195)
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/a5bf5a6c-f9dd-4a7e-9ae0-7ec2393fd354)

Can we enforce page breaks in a Markdown or is there a global fix for preventing these automatically?

**Comment by Witiko** [comment]
It's unclear to me what the issue with the first example is. In the table of contents, each line corresponds to an independent section. There is no typographic rule that would forbid page breaks between two lines in a table of contents.

The second example is something that we can fix.
