### ISSUE TITLE
Markdown tables overflow

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#30]
Some tables has tendency to overflow the page.

Example can be found in [CTAL-TA Sample Exam question 34](https://github.com/istqborg/istqb_ctal-ta/blob/dev-alpha/sample-exam/questions.yml#L808C1-L814C78)

Rendered output:
<img width="484" alt="image" src="https://github.com/istqborg/istqb_product_base/assets/95688217/404ff755-6bf6-4bf7-b0a3-e0664b4aa19b">

Code:
```markdown
| Customer | System |
| :------- | :----- |
| 1. The user visits the website.   | 2. The system shows a promotion banner prompting customers to access the new customer guide. |
| 3. The user clicks on the prompt. | 4. The system opens the guide. |
| 5. The user navigates through the guide's introductory section, learning about the website's features and layout. |     |
| 6. The user follows the guide's instructions to make a successful purchase. | 7. The system shows the purchase is completed successfully. |
| 8. The user closes the prompt.    | 9. The system closes the guide. |
```

This is most probably caused by numbered list used. Is there a fix for it?

**Comment by Witiko** [comment]
> Is there a fix for it?

The fix is two-fold:

1. In order for long cells to wrap across multiple lines, the column needs to be of type `---`. The types `:--` and `--:` are for short columns with cells that will never wrap across multiple lines.
2. If the `1.`, `2.`, `3.`, ... in the table are not supposed to signify a numbered list, escape the dot (`.`) as follows: `1\.`, `2\.`, `3\.`, ...

In conclusion, here is how you might write the above table:

``` md
| Customer | System |
| -------- | ------ |
| 1\. The user visits the website.   | 2\. The system shows a promotion banner prompting customers to access the new customer guide. |
| 3\. The user clicks on the prompt. | 4\. The system opens the guide. |
| 5\. The user navigates through the guide's introductory section, learning about the website's features and layout. |     |
| 6\. The user follows the guide's instructions to make a successful purchase. | 7\. The system shows the purchase is completed successfully. |
| 8\. The user closes the prompt.    | 9\. The system closes the guide. |
```
