### ISSUE TITLE
Add option to add line numbers to generated documents

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#54]
ISTQB requires us to provide line numbers in the generated documents for review purposes.

Currently we are using it in [CTAL-TA syllabus](https://github.com/istqborg/istqb-ctal-ta/blob/alpha-dev-syllabus/syllabus-en.tex#L15), but with mixed results.

We would like to:

1. Increase the size of line number text
2. Get the line number for every line (currently missing, e.g. for L1 and L2 headers, LOs, etc.)
3. Option to turn on the line numbers should be part of the template and documentation. But solution with a [2 lines of tex code](https://github.com/istqborg/istqb-ctal-ta/blob/alpha-dev-syllabus/syllabus-en.tex#L15) is fine.
4. Get linenumbers into EPUB and HTML is possible, or at least fix failing builds in case it's enabled. If not possible, avoid build of these formats unless it's a release version without a linenumbers.

Preview of CTAL-TA
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/b83a9efa-10d5-419d-a347-8608816e35a7)

**Comment by Witiko** [comment]
> ISTQB requires us to provide line numbers in the generated documents for review purposes.
>
> Currently we are using it in [CTAL-TA syllabus](https://github.com/istqborg/istqb-ctal-ta/blob/alpha-dev-syllabus/syllabus-en.tex#L15), but with mixed results.

Do we want to streamline this and enable the line numbers automatically based on the metadata instead of having to make changes to the `.tex` files?

> 1. Increase the size of line number text

After loading the `lineno` package, you can enlarge the font size as follows:

``` tex
\def\linenumberfont{\normalfont\normalsize\sffamily}
```

> 2. Get the line number for every line (currently missing, e.g. for L1 and L2 headers, LOs, etc.)

I don't think I know how to do that with LaTeX.

> Get linenumbers into EPUB and HTML is possible, or at least fix failing builds in case it's enabled.

In PDF documents, the layout is fixed and therefore it makes sense to display line numbers. In EPUB and HTML, the layout is responsive and different viewers will display a different number of lines. Therefore, line numbers do not seem useful as a communication tool between authors and reviewers in EPUB and HTML documents.

> If not possible, avoid build of these formats unless it's a release version without a linenumbers.

How should the CI determine that a document is a release version without linenumbers?

**Comment by danopolan** [comment]
> Do we want to streamline this and enable the line numbers automatically based on the metadata instead of having to make changes to the `.tex` files?

Yes, if that is not more than 1 hour of work. Otherwise, we can just keep the code in the template repository [as it is](https://github.com/istqborg/istqb_product_template/blob/main/syllabus.tex#L15) now.

> How should the CI determine that a document is a release version without linenumbers?

Can we base this on a metadata file?

**Comment by Witiko** [comment]
> Can we base this on a metadata file?

Definitely, it's just unclear to me whether we need to extend the current schema. Is there a way to unambiguously decide whether a document is a release version based on the value of the `release` metadata field or other metadata fields? Do we need to add another metadata field such as `draft: true|false`, `in_review: true|false`, etc.?

> We can extract this to another issue if it's a greater effort.

It is definitely a greater effort.

I can easily add built-in support for showing line numbers based on metadata, increase the font size, and fix the build of HTML and EPUB formats within 1 hour. By contrast, adding support for learning objectives and the several different types of tables that we use in our template is a research project and I have no ETA at this moment.

**Comment by danopolan** [comment]
> Definitely, it's just unclear to me whether we need to extend the current schema.

A simple rule is: if `version: release`, then there are no line numbers. But I can imagine, that some people would like to have the ability to turn on/off line numbers regardless of a version, so I would better see a new key added for this purpose. 

> I can easily add built-in support for showing line numbers based on metadata, increase the font size, and fix the build of HTML and EPUB formats within 1 hour.

So let's do this as part of current issue and do the rest in the separate issue.

**Comment by Witiko** [comment]
> A simple rule is: if `version: release`, then there are no line numbers. But I can imagine, that some people would like to have the ability to turn on/off line numbers regardless of a version, so I would better see a new key added for this purpose.

Let's add a new optional metadata key `line-numbers: true|false`. If it's specified, then we use it to decide whether we should display line numbers. Otherwise, we use the value of the `version` metadata field to decide about the line numbers.

**Comment by danopolan** [comment]
> Let's add a new optional metadata key `line-numbers: true|false`. When it's specified, we'll use it to decide whether we should display line numbers. Otherwise, we'll use the value of the `version` metadata field to decide about the line numbers.

Please, use only `line-numbers:` key. If not provided, line numbers will be false by default. Coupling with another key like `version` or `release` will cause confusion.
