### ISSUE TITLE
Citations formatting update

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#55]
We would like to change few things in the citations for improved reading experience.

1. In the case of more authors, `andothers` text in bold is displayed in the cited text. The main author should be enough in these cases.
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/4ce3de5f-47c4-4f8a-9efa-f761adb418c1)
2. The list of references, has several small formatting issues with bolt text. Can we make everything regular?
![image](https://github.com/istqborg/istqb_product_base/assets/95688217/59c37c48-fe25-4512-a51c-9e06db59c033)
3. The list of references contains text `jouvol` instead of `journal`
4. The list of references contains text `urlfromDOI` instead of `DOI`

**Comment by Witiko** [comment]
This seems like a missing translation. Which document do your screenshots come from?

**Comment by danopolan** [comment]
It's CTAL-TA
https://github.com/istqborg/istqb-ctal-ta/actions/runs/9291834438

**Comment by Witiko** [comment]
This issue seems caused by PR https://github.com/istqborg/istqb_product_base/pull/42, which deferred the loading of language definitions that caused an issue with loading the localized strings used in the bibliographic references.
