### ISSUE TITLE
Remove questions in YAML format from DOCX output

### ISSUE THREAD

**Issue by danopolan** [istqborg/istqb_product_base#91]
Currently, the DOCX output of Sample Exams contains:

- MD files `copyright.md`, `revisions.md`, etc.
- YAML format of questions (previously `questions.yml`) - **should be removed**
- MD format of questions as `questions.md`

Additionally, there are two more minor changes I would like to request:
1. the same DOCX file is generated twice as `sample-exam-answers.docx` and `sample-exam-questions.docx`
2. Naming of the files could respect naming as for PDF outputs. This applies to HTML and EPUB as well.

See https://github.com/istqborg/istqb-ctal-ta/actions/runs/10264340269 to see the current DOCX output.

**Comment by Witiko** [comment]
@danopolan All changes seem well-defined and easy to add, except the following:

> 1. the same DOCX file is generated twice as `sample-exam-answers.docx` and `sample-exam-questions.docx`

`sample-exam-answers.docx` and `sample-exam-questions.docx` are two distinct TeX documents. The set of dependent MD and YAML files will be the same after the resolution of symlinks, so we might convert just one of them to DOCX (which one?) but it seems like a lot of extra code just to cover just this corner case. I suggest either 1) having a separate metadata file with `docx-output: false` for one of the files or just 2) ignoring the second `.docx` file in the artefacts. Would this be an option for you?
